import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Filip',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
    },
    {
      name: 'Stefan',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
    },
    {
      name: 'Sasa',
      email: 'admin3@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: false,
    },
  ],
  products: [
    {
      name: 'Naruto Uzumaki01',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 10,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Naruto Uzumaki02',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 10,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Naruto Uzumaki03',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 10,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Naruto Uzumaki04',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 0,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Naruto Uzumaki05',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 12,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Naruto Uzumaki06',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 1,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
