const data = {
  products: [
    {
      _id: '1',
      name: 'Naruto Uzumaki',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 10,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Naruto Uzumaki',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 10,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Naruto Uzumaki',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 10,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Naruto Uzumaki',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 0,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Naruto Uzumaki',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 12,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Naruto Uzumaki',
      category: 'Statues',
      image: '/images/p1.jpg',
      price: 899,
      countInStock: 1,
      brand: 'Mangado-Collectors',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
